export default [
  {
    task_id: 0,
    requester_id: 0,
    helper_id: 0,
    location: {
      street_address: '',
      city: '',
      state: '',
      zipcode: '',
      coordinate: '(-118.2605499,34.0775885)',
    },
    description: '',
    car_required: false,
    status: 'Open',
    category: '',
    start_date: '2021-08-13T07:00:00.000Z',
    start_time: '22:30:13',
    timestamp_requested: '2021-07-15',
    duration: 0,
    requester: {
      id: 0,
      firstname: '',
      lastname: '',
      address_id: 0,
      karma: 0,
      response_count: 0,
      average_rating: 0,
      profile_picture_url: '',
    },
    helper: {
      id: 0,
      firstname: '',
      lastname: '',
      address_id: 0,
      karma: 0,
      response_count: 0,
      average_rating: 0,
      profile_picture_url: '',
    },
  },
];
