export default {
  testTasks: [
    {
      task_id: 1,
      requester_id: 1,
      helper_id: null,
      address_id: 1,
      description: 'I need someone to come check on my dogs once a day for the next three days. They are very friendly. Two small poodles, hypoallergenic, about 20 pounds each. Just need somone to make sure their water bowls are filled. Thank you guys!',
      car_required: false,
      status: 'unclaimed',
      category: 'sitter',
      date: null,
      time: null,
      date_requested: null,
      duration: null,
    },
    {
      task_id: 2,
      requester_id: 9,
      helper_id: null,
      address_id: 1,
      description: 'I just have a few questions. Would love a second of your time',
      car_required: false,
      status: 'unclaimed',
      category: 'sitter',
      date: null,
      time: null,
      date_requested: null,
      duration: null,
    },
    {
      task_id: 3,
      requester_id: 8,
      helper_id: null,
      address_id: 1,
      description: 'I need someone to come check on my dogs once a day for the next three days. They are very friendly. Two small poodles, hypoallergenic, about 20 pounds each. Just need somone to make sure their water bowls are filled. Thank you guys!',
      car_required: false,
      status: 'unclaimed',
      category: 'sitter',
      date: null,
      time: null,
      date_requested: null,
      duration: null,
    },
    {
      task_id: 4,
      requester_id: 7,
      helper_id: null,
      address_id: 1,
      description: 'I need someone to come check on my dogs once a day for the next three days. They are very friendly. Two small poodles, hypoallergenic, about 20 pounds each. Just need somone to make sure their water bowls are filled. Thank you guys!',
      car_required: false,
      status: 'unclaimed',
      category: 'sitter',
      date: null,
      time: null,
      date_requested: null,
      duration: null,
    },
    {
      task_id: 5,
      requester_id: 6,
      helper_id: null,
      address_id: 1,
      description: 'I need someone to come check on my dogs once a day for the next three days. They are very friendly. Two small poodles, hypoallergenic, about 20 pounds each. Just need somone to make sure their water bowls are filled. Thank you guys!',
      car_required: false,
      status: 'unclaimed',
      category: 'sitter',
      date: null,
      time: null,
      date_requested: null,
      duration: null,
    },
    {
      task_id: 6,
      requester_id: 5,
      helper_id: null,
      address_id: 1,
      description: 'I need someone to come check on my dogs once a day for the next three days. They are very friendly. Two small poodles, hypoallergenic, about 20 pounds each. Just need somone to make sure their water bowls are filled. Thank you guys!',
      car_required: false,
      status: 'unclaimed',
      category: 'sitter',
      date: null,
      time: null,
      date_requested: null,
      duration: null,
    },
    {
      task_id: 7,
      requester_id: 4,
      helper_id: null,
      address_id: 1,
      description: 'I need someone to come check on my dogs once a day for the next three days. They are very friendly. Two small poodles, hypoallergenic, about 20 pounds each. Just need somone to make sure their water bowls are filled. Thank you guys!',
      car_required: false,
      status: 'unclaimed',
      category: 'sitter',
      date: null,
      time: null,
      date_requested: null,
      duration: null,
    },
    {
      task_id: 8,
      requester_id: 3,
      helper_id: null,
      address_id: 1,
      description: 'I need someone to come check on my dogs once a day for the next three days. They are very friendly. Two small poodles, hypoallergenic, about 20 pounds each. Just need somone to make sure their water bowls are filled. Thank you guys!',
      car_required: false,
      status: 'unclaimed',
      category: 'sitter',
      date: null,
      time: null,
      date_requested: null,
      duration: null,
    },
  ],

  testUsers: [
    {
      id: 1,
      firstname: 'Huge',
      lastname: 'Jackedman',
      address_id: 1,
      karma: 5,
      response_count: 24,
      average_rating: 4.7,
      profile_picture: 'https://www.indiewire.com/wp-content/uploads/2017/06/0000246240.jpg',
    },
    {
      id: 2,
      firstname: 'Sandra',
      lastname: 'Bollox',
      address_id: 2,
      karma: 5,
      response_count: 24,
      average_rating: 4.7,
      profile_picture: 'https://www.indiewire.com/wp-content/uploads/2017/06/0000246240.jpg',
    },
    {
      id: 3,
      firstname: 'Brie',
      lastname: 'Larson',
      address_id: 2,
      karma: 5,
      response_count: 24,
      average_rating: 4.7,
      profile_picture: 'https://www.indiewire.com/wp-content/uploads/2017/06/0000246240.jpg',
    },
    {
      id: 4,
      firstname: 'Anna',
      lastname: 'Arrendelle',
      address_id: 2,
      karma: 5,
      response_count: 24,
      average_rating: 4.7,
      profile_picture: 'https://www.indiewire.com/wp-content/uploads/2017/06/0000246240.jpg',
    },
    {
      id: 5,
      firstname: 'Benjamin',
      lastname: 'Franklin-Gates',
      address_id: 2,
      karma: 5,
      response_count: 24,
      average_rating: 4.7,
      profile_picture: 'https://www.indiewire.com/wp-content/uploads/2017/06/0000246240.jpg',
    },
    {
      id: 6,
      firstname: 'Kirk',
      lastname: 'Lazarus',
      address_id: 2,
      karma: 5,
      response_count: 24,
      average_rating: 4.7,
      profile_picture: 'https://www.indiewire.com/wp-content/uploads/2017/06/0000246240.jpg',
    },
    {
      id: 7,
      firstname: 'Jordan',
      lastname: 'Belfort',
      address_id: 2,
      karma: 5,
      response_count: 24,
      average_rating: 4.7,
      profile_picture: 'https://www.indiewire.com/wp-content/uploads/2017/06/0000246240.jpg',
    },
    {
      id: 8,
      firstname: 'Brad',
      lastname: 'Smith',
      address_id: 2,
      karma: 5,
      response_count: 24,
      average_rating: 4.7,
      profile_picture: 'https://www.indiewire.com/wp-content/uploads/2017/06/0000246240.jpg',
    },
    {
      id: 9,
      firstname: 'Jennifer',
      lastname: 'Cho',
      address_id: 2,
      karma: 5,
      response_count: 24,
      average_rating: 4.7,
      profile_picture: 'https://www.indiewire.com/wp-content/uploads/2017/06/0000246240.jpg',
    },
  ],
};
