export const testTasks = [
  {
    task_id: 0,
    requester_id: 0,
    helper_id: null,
    location: {
      street_address: '',
      city: '',
      state: '',
      zipcode: '',
      coordinate: '(-118.2605499,34.0775885)',
    },
    description: '',
    car_required: false,
    status: 'Open',
    category: '',
    start_date: '2021-08-13T07:00:00.000Z',
    start_time: '22:30:13',
    timestamp_requested: '2021-07-15',
    duration: 0,
    requester: {
      id: 0,
      firstname: '',
      lastname: '',
      address_id: 0,
      karma: 0,
      response_count: 0,
      average_rating: 0,
      profile_picture_url: '',
    },
  },
];

export const potato = {
  testTask2: [
    {
      task_id: 1,
      requester_id: 1,
      helper_id: null,
      address: {
        streetAddress: '727 N Broadway',
        city: 'Los Angeles',
        state: 'CA',
        zipcode: '90012',
      },
      description: 'I need someone to come check on my dogs once a day for the next three days. They are very friendly. Two small poodles, hypoallergenic, about 20 pounds each. Just need somone to make sure their water bowls are filled. Thank you guys!',
      car_required: true,
      status: 'Open',
      category: 'sitter',
      start_date: '2021-08-13T07:00:00.000Z',
      time: '22:30:13',
      timestamp_requested: '2021-07-15',
      duration: 'Short: < 1 hour',
      requester: {
        id: 1,
        firstname: 'Huge',
        lastname: 'Jackedman',
        address_id: 1,
        karma: 5,
        response_count: 24,
        average_rating: 4.7,
        profile_picture_url: 'https://www.indiewire.com/wp-content/uploads/2017/06/0000246240.jpg',
      },
    },
    {
      task_id: 2,
      requester_id: 9,
      helper_id: null,
      address: {
        streetAddress: '727 N Broadway',
        city: 'Los Angeles',
        state: 'CA',
        zipcode: '90012',
      },
      description: 'I just have a few questions. Would love a second of your time',
      car_required: false,
      status: 'Open',
      category: 'sitter',
      start_date: '2021-08-13T07:00:00.000Z',
      time: '12:30:13',
      timestamp_requested: '2021-07-15',
      duration: 'Short: < 1 hour',
      requester: {
        id: 9,
        firstname: 'Jennifer',
        lastname: 'Cho',
        address_id: 2,
        karma: 5,
        response_count: 24,
        average_rating: 4.7,
        profile_picture_url: 'https://media-exp1.licdn.com/dms/image/C5603AQEVw__BKGBOdw/profile-displayphoto-shrink_200_200/0/1551395086203?e=1631750400&v=beta&t=yMuQBb8y5FTMWUZfBUKUFvACe8Mbv5z_8aaCAQxaSH0',
      },
    },
    {
      task_id: 3,
      requester_id: 8,
      helper_id: null,
      address: {
        streetAddress: '727 N Broadway',
        city: 'Los Angeles',
        state: 'CA',
        zipcode: '90012',
      },
      description: 'Need help moving my couch',
      car_required: false,
      status: 'Completed',
      category: 'sitter',
      start_date: '2021-08-13T07:00:00.000Z',
      time: '09:00:13',
      timestamp_requested: '2021-07-15',
      duration: 'Short: < 1 hour',
      requester: {
        id: 2,
        firstname: 'Sandra',
        lastname: 'Bollox',
        address_id: 2,
        karma: 5,
        response_count: 24,
        average_rating: 4.7,
        profile_picture_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_KU7SGQ9-7BMTsea4Vgs8qwDa_sbnjZ3e-Q&usqp=CAU',
      },
    },
    {
      task_id: 4,
      requester_id: 7,
      helper_id: 2,
      address: {
        streetAddress: '727 N Broadway',
        city: 'Los Angeles',
        state: 'CA',
        zipcode: '90012',
      },
      description: 'Can I borrow a vacuum? Mine broke',
      car_required: false,
      status: 'Pending',
      category: 'sitter',
      start_date: '2021-08-13T07:00:00.000Z',
      time: '12:00:13',
      timestamp_requested: '2021-07-15',
      duration: 'Short: < 1 hour',
      requester: {
        id: 3,
        firstname: 'Brie',
        lastname: 'Larson',
        address_id: 2,
        karma: 5,
        response_count: 24,
        average_rating: 4.7,
        profile_picture_url: 'https://www.indiewire.com/wp-content/uploads/2019/03/shutterstock_10139128cg.jpg',
      },
    },
    {
      task_id: 5,
      requester_id: 6,
      helper_id: null,
      address: {
        streetAddress: '727 N Broadway',
        city: 'Los Angeles',
        state: 'CA',
        zipcode: '90012',
      },
      description: 'I need some emergency makeup (dark foundation)',
      car_required: false,
      status: 'Pending',
      category: 'sitter',
      start_date: '2021-08-13T07:00:00.000Z',
      time: '06:30:13',
      timestamp_requested: '2021-07-15',
      duration: 'short: < 1 hour',
      requester: {
        id: 6,
        firstname: 'Kirk',
        lastname: 'Lazarus',
        address_id: 2,
        karma: 5,
        response_count: 24,
        average_rating: 4.7,
        profile_picture_url: 'https://pbs.twimg.com/media/DhVpQ4yWsAA_Qra.jpg',
      },
    },
    {
      task_id: 6,
      requester_id: 5,
      helper_id: null,
      address: {
        streetAddress: '727 N Broadway',
        city: 'Los Angeles',
        state: 'CA',
        zipcode: '90012',
      },
      description: 'Need help moving a couch',
      car_required: false,
      status: 'Pending',
      category: 'sitter',
      start_date: '2021-08-13T07:00:00.000Z',
      time: '06:50:13',
      timestamp_requested: '2021-07-15',
      duration: 'Short: < 1 hour',
      requester: {
        id: 4,
        firstname: 'Anna',
        lastname: 'Arrendelle',
        address_id: 2,
        karma: 5,
        response_count: 24,
        average_rating: 4.7,
        profile_picture_url: 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F14%2F2019%2F05%2F15%2F051019-kristen-bell-money-talks-lead.jpg&q=85',
      },
    },
    {
      task_id: 7,
      requester_id: 2,
      helper_id: null,
      address: {
        streetAddress: '727 N Broadway',
        city: 'Los Angeles',
        state: 'CA',
        zipcode: '90012',
      },
      description: 'I need friends pls.',
      car_required: false,
      status: 'Pending',
      category: 'sitter',
      start_date: '2021-08-13T07:00:00.000Z',
      time: '11:00:13',
      timestamp_requested: '2021-07-15',
      duration: 'Short: < 1 hour',
      requester: {
        id: 7,
        firstname: 'Jordan',
        lastname: 'Belfort',
        address_id: 2,
        karma: 5,
        response_count: 24,
        average_rating: 4.7,
        profile_picture_url: 'https://www.biography.com/.image/t_share/MTgwNDU1MTIxMTE1Njg2NzY0/gettyimages-1197345888.jpg',
      },
    },
    {
      task_id: 8,
      requester_id: 2,
      helper_id: null,
      address: {
        streetAddress: '727 N Broadway',
        city: 'Los Angeles',
        state: 'CA',
        zipcode: '90012',
      },
      description: 'Need some emergency lemons! Will pay',
      car_required: false,
      status: 'Pending',
      category: 'sitter',
      start_date: '2021-08-13T07:00:00.000Z',
      time: '01:45:13',
      timestamp_requested: '2021-07-15',
      duration: 'Short: < 1 hour',
      requester: {
        id: 5,
        firstname: 'Benjamin',
        lastname: 'Franklin-Gates',
        address_id: 2,
        karma: 5,
        response_count: 24,
        average_rating: 4.7,
        profile_picture_url: 'https://api.time.com/wp-content/uploads/2015/07/nicolas-cage1.jpg',
      },
    },
    {
      task_id: 9,
      requester_id: 2,
      helper_id: null,
      address: {
        streetAddress: '727 N Broadway',
        city: 'Los Angeles',
        state: 'CA',
        zipcode: '90012',
      },
      description: 'I need some forks for a dinner party',
      car_required: false,
      status: 'Open',
      category: 'sitter',
      start_date: '2021-08-13T07:00:00.000Z',
      time: '01:45:13',
      timestamp_requested: '2021-07-15',
      duration: 'Short: < 1 hour',
      requester: {
        id: 2,
        firstname: 'Sandra',
        lastname: 'Bollox',
        address_id: 2,
        karma: 5,
        response_count: 24,
        average_rating: 4.7,
        profile_picture_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_KU7SGQ9-7BMTsea4Vgs8qwDa_sbnjZ3e-Q&usqp=CAU',
      },
    },
    {
      task_id: 10,
      requester_id: 2,
      helper_id: null,
      address: {
        streetAddress: '727 N Broadway',
        city: 'Los Angeles',
        state: 'CA',
        zipcode: '90012',
      },
      description: 'Can someone walk my dog tomorrow?',
      car_required: false,
      status: 'Pending',
      category: 'sitter',
      start_date: '2021-08-13T07:00:00.000Z',
      time: '01:45:13',
      timestamp_requested: '2021-07-15',
      duration: 'Short: < 1 hour',
      requester: {
        id: 2,
        firstname: 'Sandra',
        lastname: 'Bollox',
        address_id: 2,
        karma: 5,
        response_count: 24,
        average_rating: 4.7,
        profile_picture_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_KU7SGQ9-7BMTsea4Vgs8qwDa_sbnjZ3e-Q&usqp=CAU',
      },
    },
  ],

  testrequesters: [
    {
      id: 1,
      firstname: 'Huge',
      lastname: 'Jackedman',
      address_id: 1,
      karma: 5,
      response_count: 24,
      average_rating: 4.7,
      profile_picture_url: 'https://www.indiewire.com/wp-content/uploads/2017/06/0000246240.jpg',
    },
    {
      id: 2,
      firstname: 'Sandra',
      lastname: 'Bollox',
      address_id: 2,
      karma: 5,
      response_count: 24,
      average_rating: 4.7,
      profile_picture_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_KU7SGQ9-7BMTsea4Vgs8qwDa_sbnjZ3e-Q&usqp=CAU',
    },
    {
      id: 3,
      firstname: 'Brie',
      lastname: 'Larson',
      address_id: 2,
      karma: 5,
      response_count: 24,
      average_rating: 4.7,
      profile_picture_url: 'https://www.indiewire.com/wp-content/uploads/2019/03/shutterstock_10139128cg.jpg',
    },
    {
      id: 4,
      firstname: 'Anna',
      lastname: 'Arrendelle',
      address_id: 2,
      karma: 5,
      response_count: 24,
      average_rating: 4.7,
      profile_picture_url: 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F14%2F2019%2F05%2F15%2F051019-kristen-bell-money-talks-lead.jpg&q=85',
    },
    {
      id: 5,
      firstname: 'Benjamin',
      lastname: 'Franklin-Gates',
      address_id: 2,
      karma: 5,
      response_count: 24,
      average_rating: 4.7,
      profile_picture_url: 'https://api.time.com/wp-content/uploads/2015/07/nicolas-cage1.jpg',
    },
    {
      id: 6,
      firstname: 'Kirk',
      lastname: 'Lazarus',
      address_id: 2,
      karma: 5,
      response_count: 24,
      average_rating: 4.7,
      profile_picture_url: 'https://pbs.twimg.com/media/DhVpQ4yWsAA_Qra.jpg',
    },
    {
      id: 7,
      firstname: 'Jordan',
      lastname: 'Belfort',
      address_id: 2,
      karma: 5,
      response_count: 24,
      average_rating: 4.7,
      profile_picture_url: 'https://www.biography.com/.image/t_share/MTgwNDU1MTIxMTE1Njg2NzY0/gettyimages-1197345888.jpg',
    },
    {
      id: 8,
      firstname: 'Brad',
      lastname: 'Smith',
      address_id: 2,
      karma: 5,
      response_count: 24,
      average_rating: 4.7,
      profile_picture_url: 'https://www.biography.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1200/MTY3MDUxMjkzMjI1OTIwMTcz/brad-pitt-attends-the-premiere-of-20th-century-foxs--square.jpg',
    },
    {
      id: 9,
      firstname: 'Jennifer',
      lastname: 'Cho',
      address_id: 2,
      karma: 5,
      response_count: 24,
      average_rating: 4.7,
      profile_picture_url: 'https://media-exp1.licdn.com/dms/image/C5603AQEVw__BKGBOdw/profile-displayphoto-shrink_200_200/0/1551395086203?e=1631750400&v=beta&t=yMuQBb8y5FTMWUZfBUKUFvACe8Mbv5z_8aaCAQxaSH0',
    },
  ],
};
